### ISSUE TITLE
Doesnt like multi branch configurations

### ISSUE THREAD

**Issue by myoung34** [Gradiant/slack-notifier-jenkins-sl#2]
The branch comes out as `null` and the Job name is URL encoded for multi branch builds on builds such as "Thing Doer"

```
Thing%20Doer » null - #1 An error occurred :interrobang: (Open)
```

**Comment by vilasmaciel** [comment]
Hi @myoung34, my apologies for being so late at fixing this issue, we had not set up issue notifications.

The problem was solved with the new release v1.0.1.

Thanks for sharing!
